name: nock
description: HTTP requests mocking library for dart and flutter. Test your application in isolation.
version: 1.2.3
homepage: https://github.com/cah4a/dart_nock

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  test: any
  collection: any

dev_dependencies:
  http: any
  pedantic: any
